# Generated by Django 3.0.3 on 2020-02-23 14:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_type", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.DecimalField(decimal_places=2, max_digits=10)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("timestamp", models.IntegerField(default=0)),
                (
                    "ptype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product_type.ProductType",
                    ),
                ),
            ],
        ),
    ]
