# Generated by Django 3.0.3 on 2020-02-24 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rformat",
                    models.CharField(
                        choices=[("D", "DAY"), ("M", "MONTH"), ("Y", "YEAR")],
                        max_length=1,
                    ),
                ),
                ("total", models.TextField(default="{}")),
                ("summary", models.TextField(default="{}")),
                ("meta", models.TextField(default="{}")),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
