# Generated by Django 3.0.3 on 2020-02-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcache", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="djangocache",
            index=models.Index(fields=["expires"], name="django-cache_expires"),
        ),
    ]
